### ISSUE TITLE
robtk content missing?

### ISSUE THREAD

**Issue by BillScherer** [x42/scarlett-mixer#1]
scherbi@scarlett ~/s/scarlett-mixer> make
make: *** No rule to make target 'robtk/robtkapp.c', needed by 'scarlett-mixer'.  Stop.

**Comment by x42** [comment]
Did you get the robtk git submodule? see  https://github.com/x42/scarlett-mixer#readme

**Comment by BillScherer** [comment]
Got it now. That was a little confusing. Thanks.

**Comment by BillScherer** [comment]
Builds clean. Now I just need to wait until my 18i20 comes back from repair, then I will edit and see if I can get it running!

**Comment by x42** [comment]
OK. I'll close this, then.

PS. I've meanwhile started to prepare the tool for other Scarlett devices. The GUI layout now just uses `#define` values and I've left some notes for the mapping.
