### ISSUE TITLE
Segmentation fault - 18i20

### ISSUE THREAD

**Issue by MarcosRava** [x42/scarlett-mixer#18]
When I try to run
```
./scarlett-mixer -v
```
I receive this msg:
```
Autodetect: Using "hw:3"
Segmentation fault
```
```
aplay -l

card 3: USB [Scarlett 18i20 USB], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

OS: KXStudio

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty

**Comment by x42** [comment]
Probably the same as #16  (assuming this is not a 1st generation Scarlett device)

**Comment by MarcosRava** [comment]
this is the 1st generation ._.

I tried on ubuntu 20.04 and works fine! tks!
