### ISSUE TITLE
18i20 debug output

### ISSUE THREAD

**Issue by BillScherer** [x42/scarlett-mixer#6]
STDERR:
Device `hw:2' is not supported
Device `Scarlett 18i20 USB' has 214 contols: 
Error: GUI was not initialized.
bye.
STDOUT:
[18i20.txt](https://github.com/x42/scarlett-mixer/files/1687617/18i20.txt)

**Comment by x42** [comment]
Thanks, I've added support based on the data-dump.  I don't see any `pad` nor `impedance` software switches. Is that correct for the device?

I'm also curious how the GUI layout will work, 10 stereo pair outputs in a single row at the bottom will likely not work very well.  That may need to be split into two rows.

**Comment by BillScherer** [comment]
I've never run the official mixer, not having an O/S that supports it. I have never seen any pad nor impedance controls in the alsa mixer, nor in the doc.

As for the gui, two rowsshould be fine...but, maybe their visibility could be toggled?

**Comment by x42** [comment]
Could you provide have a screenshot (I'm curious)?

The official mixer is quite different, it doesn't expose the raw controls as a matrix but does a logical layout on top of it.

**Comment by BillScherer** [comment]
![18i20](https://user-images.githubusercontent.com/17678283/35710602-66f0037e-0786-11e8-974c-a6cdefb49934.png)

**Comment by x42** [comment]
Thanks it, looks like I've missed the channel assign for 9/10 .. ADAT as well.

**Comment by BillScherer** [comment]
did I pull too soon?

> ./scarlett-mixer 
scarlett-mixer: ./src/scarlett_mixer.c:261: out_gain: Assertion `c < MAX_GAINS' failed.
fish: “./scarlett-mixer” terminated by signal SIGABRT (Abort)

**Comment by x42** [comment]
hang on..

**Comment by x42** [comment]
Should be good now (I'll keep my fingers crossed).

As for the GUI (multi-row or hide) that'll have to wait for another day.

**Comment by BillScherer** [comment]
sorry:

scherbi@scarlett ~/s/scarlett-mixer> ./scarlett-mixer 
scarlett-mixer: ./src/scarlett_mixer.c:502: get_enum: Assertion `snd_mixer_selem_is_enumerated (c->elem)' failed.
fish: “./scarlett-mixer” terminated by signal SIGABRT (Abort)
scherbi@scarlett ~/s/scarlett-mixer>

**Comment by x42** [comment]
please `git pull`, again :)

**Comment by BillScherer** [comment]
![18i20](https://user-images.githubusercontent.com/17678283/35711304-4e1fc880-078a-11e8-82ce-5d510a423a9b.png)

**Comment by x42** [comment]
Now that looks better. Have fun routing!

**Comment by BillScherer** [comment]
Will do! Thanks! One suggestion...with so many sources to route from, the one by one click on the controls is a bit slow sometimes. Perhaps an accelerator, or a drop down list, or some such?

**Comment by x42** [comment]
You can mouse-wheel on a control to move fast.  Dropdowns are not planned in the GUI toolkit (since that would be a popup window or might exceed the window-space).

Right-click on any knob toggles default + last value.  Left-click on the output knobs toggles mute.

Let me know if the controls work properly:
Top-left side defines which channels are routed to the 18 inputs which the DAW (or jack) sees.
The bottom row is for output assign (which can be zero-latency direct inputs or any matrix output).

I'm kinda 50/50 on further development. I've hacked up this UI a few years ago for my own use and never really planned to publish it nor spend much time on developing it further..  but if it's useful for others who knows: The source is out there.

**Comment by BillScherer** [comment]
Controls work perfectly as described!

Understood. Thanks so much for this, it helps a lot!

**Comment by x42** [comment]
With some luck, outputs should be multi-row now...

**Comment by BillScherer** [comment]
oh sweet. will check it out in a while.

**Comment by x42** [comment]
Forgot to mention: with middle-click you can assign a row in the matrix to a single source (actually toggle/clear a row). I'll update the man-page and `--help` output to describe the controls.

**Comment by BillScherer** [comment]
cool. I will check it out tomorrow. Thanks!

**Comment by matze** [comment]
> I'm kinda 50/50 on further development. I've hacked up this UI a few years ago for my own use and never really planned to publish it nor spend much time on developing it further.. but if it's useful for others who knows: The source is out there.

I've not much experience with RobTk (either it's bit under-documented or I just cannot find any) but how hard would it be to add saving and loading of mixes? Recalling common mix situations would be a tremendous help especially since the interface itself does not remember anything after turning it off.

**Comment by x42** [comment]
I just use `alsactl` to load/save presets (`--file`).

robtk came to be specifically for plugins (allow static linking, self contained) and it was just quick to re-use if for this mixer-ui. Alas, there's indeed near zero documentation (although it lends some concepts from gtk2)

**Comment by matze** [comment]
> I just use alsactl to load/save presets (--file).

Thanks, that will do it :+1:

**Comment by BillScherer** [comment]
It's looking great. Not sure if it's me, or if the mixer is not working. I have a mic on analog 1, and the meter on the 18i20 deflects when I speak into it. I believe I have analog 1 routed to mix A and mix B (and some in C thru H as well), and I have mix A/B going to Monitor, and also to 9/10. With either monitor or 9/10 connect to my power amp, I get nothing.
![mixer](https://user-images.githubusercontent.com/17678283/35756018-9992c36e-0837-11e8-8739-be53fff7c1c2.png)

**Comment by BillScherer** [comment]
well, strange. I seemed to recall having to go into alsamixer and toggle the clock source or some such...the right most 1 or two controls. I did that, and now I get output.

**Comment by BillScherer** [comment]
Oh, I am ever so happy now. It's working perfectly. So now I can run guitar/bass/keys/vocals into analog 1 through 4, and have that pass through directly to lines out 1,2,3,4, which go to the first 4 channels on my Allen & Heath Zed10FX. Drum mics will go into analog 5,6,7,8, and get mixed in scarlett-mixer to mix A/B, which is routed out 9/10, to a ST1 (stereo input) on the Zed10. In this way, I can record 8 individual tracks (analog 1-8) via the 18i20's usb connection, and do a live mix on the Zed10. I probably won't get to employ this setup until the spring or summer time, but so nice to know it works! Thank you!!!

**Comment by x42** [comment]
All the individual outs are muted (red color) in the screenshot. (left click to toggle)

**Comment by BillScherer** [comment]
![mixer2](https://user-images.githubusercontent.com/17678283/35757948-6839d200-083f-11e8-8dcb-929dc371247d.png)
working!

**Comment by BillScherer** [comment]
I see the toggle working now:
![mixer3](https://user-images.githubusercontent.com/17678283/35757986-9de98706-083f-11e8-8b58-5298659ce4be.png)

**Comment by x42** [comment]
It's an interesting routing situation that you describe.  sum drums in the scarlett and pass instruments through directly.  it's definitely handy to have 10 line outputs.

"..now I can run.." -- well, you could  do it with the alsamixer alone without a fancy GUI. Although with some 200+ individual controls that's definitely much less fun and a lot more confusing..

**Comment by BillScherer** [comment]
yeah, attempting to set that up in alsamixer was nightmare inducing.

The routing I describe will allow me to record my son and what ever band he might be playing with when he needs me to supply the PA for the gig. I can do the live mixing as needed, and still record individual tracks. It's nirvana!

**Comment by ensonic** [comment]
Btw. wrt to pad and impedance switches:
https://github.com/torvalds/linux/blame/master/sound/usb/mixer_scarlett.c#L806
Those are commented out on the kernel driver side for the 18i20. git blame does not tell why, probably not enough information. I'll try to dig more.
